# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.VisualStudio.2022.Professional
PackageVersion: 17.14.19
InstallerSwitches:
  Silent: --quiet
  SilentWithProgress: --passive
  Upgrade: update
  Custom: --wait
ExpectedReturnCodes:
- InstallerReturnCode: 1001
  ReturnResponse: installInProgress
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 1618
  ReturnResponse: installInProgress
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 1003
  ReturnResponse: fileInUse
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5004
  ReturnResponse: cancelledByUser
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8001
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8002
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8003
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8004
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8005
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8007
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8008
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8009
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: -1073720687
  ReturnResponse: noNetwork
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: -2146233083
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 740
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5001
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5002
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5003
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5005
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5007
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5008
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8006
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
Commands:
- devenv
AppsAndFeaturesEntries:
- DisplayVersion: '17.14.19 '
Installers:
- Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/5011a9cc-e8ef-42cb-ad72-87de1031accc/9cac5a91262639596f5e8ce19556035b620a112f00bacebad57d4df9f40b985f/vs_Professional.exe
  InstallerSha256: 9cac5a91262639596f5e8ce19556035b620a112f00bacebad57d4df9f40b985f
ManifestType: installer
ManifestVersion: 1.9.0
