# Automatically updated by the winget bot at 2021/Nov/21
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: cryptofyre.AppleMusicElectron
PackageVersion: 3.0.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Apple-Music-Electron/Apple-Music-Electron/releases/download/v3.0.0/Apple.Music.Setup.3.0.0.exe
  InstallerSha256: AE19A137CD7DBB26380B323DB07894052A065D85C17120A7938D7CF3FEF01B8D
ManifestType: installer
ManifestVersion: 1.0.0
