# Automatically updated by the winget bot at 2021/Nov/21
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: BitSum.ParkControl
PackageVersion: 1.6.0.10
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://dl.bitsum.com/files/parkcontrolsetup64.exe
  InstallerSha256: 1F05F32A620FC87B5797B6F2A4BAC1DA2C21AEBB0E9FF2934A44CC7D029DE4F7
ManifestType: installer
ManifestVersion: 1.0.0
