# Automatically updated by the winget bot at 2021/Nov/21
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: BitSum.ParkControl
PackageVersion: 1.6.0.10
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0
